import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const app=express();
app.use(express.json({limit:'20mb'}));
app.use(express.static(path.join(__dirname,'public')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=process.env.PORT||10000;
app.listen(port,()=>console.log(`RAON ERP v13 Gold Master 13.1.1 quote filter fix running on port ${port}`));
